### ISSUE TITLE
Handling with multiple sub projects

### ISSUE THREAD

**Issue by Johannes-Nyfeler** [BFH-Gsteig-Developers/CFD#5]

**Comment by Benjamin-Loeffel** [comment]
Attention: If a case is inherit from another setup, the case gets overwritten when exporting ensight case gold. So forsee an automatic generation of a new case folder when one already exists to copy the newone into.

**Comment by Benjamin-Loeffel** [comment]
Copying behaves strange

**Comment by Benjamin-Loeffel** [comment]
Problem is:
/FFF*/Fluent
/FFF*/MECH

Both can contain exported data
